### ISSUE TITLE
client.getDiscoInfo broken in 7.0.1 (6eee99e)

### ISSUE THREAD

**Issue by kdex** [legastero/stanza.io#71] opened 2014-12-30 04:15 UTC
I've noticed a small non-determinism when calling `client.getDiscoInfo()`.

When `client.getDiscoInfo()` is executed in 7.0.1 providing it the client's own full JID, sometimes the discoInfo returned is an empty object (that is: There aren't even fields such as `features`, `extensions`, etc.).

Given this call:

```
client.getDiscoInfo("anon@kdex.de/ratchet-84ea08c8-c332-410d-8965-03f340dcbfb1", null, function(error, reply) {
    console.warn("Here is the discoInfo: ", reply.discoInfo);
});
```

The raw responses look like this:

```
raw:outgoing <iq xmlns="jabber:client" to="anon@kdex.de/ratchet-84ea08c8-c332-410d-8965-03f340dcbfb1" type="get" id="6de5f060-4ef2-469d-a932-c544854797d2"><query xmlns="http://jabber.org/protocol/disco#info"/></iq>
raw:outgoing <r xmlns="urn:xmpp:sm:3"/>
iq:get:discoInfo Object {discoInfo: Object, id: "6de5f060-4ef2-469d-a932-c544854797d2", to: 235.n.JID, from: 235.n.JID, type: "get"…}
iq Object {discoInfo: Object, id: "6de5f060-4ef2-469d-a932-c544854797d2", to: 235.n.JID, from: 235.n.JID, type: "get"…}
stanza Object {discoInfo: Object, id: "6de5f060-4ef2-469d-a932-c544854797d2", to: 235.n.JID, from: 235.n.JID, type: "get"…}
id:6de5f060-4ef2-469d-a932-c544854797d2 Object {discoInfo: Object, id: "6de5f060-4ef2-469d-a932-c544854797d2", to: 235.n.JID, from: 235.n.JID, type: "get"…}
stream:data i {xml: n, _extensions: Object, _name: "iq", _eventname: undefined, _NS: "jabber:client"…}
 raw:incoming <iq type='get' to='anon@kdex.de/ratchet-84ea08c8-c332-410d-8965-03f340dcbfb1' from='anon@kdex.de/ratchet-84ea08c8-c332-410d-8965-03f340dcbfb1' id='6de5f060-4ef2-469d-a932-c544854797d2' xmlns='jabber:client'><query xmlns='http://jabber.org/protocol/disco#info'/></iq>
 Here is the discoInfo:  Object {}
 raw:outgoing <iq xmlns="jabber:client" to="anon@kdex.de/ratchet-84ea08c8-c332-410d-8965-03f340dcbfb1" id="6de5f060-4ef2-469d-a932-c544854797d2" type="result"><query xmlns="http://jabber.org/protocol/disco#info"><identity category="client" type="web"/></query></iq>
 stream:management:ack Object {h: 28}
stanza:acked i {xml: n, _extensions: Object, _name: "iq", _eventname: undefined, _NS: "jabber:client"…}
stream:data i {xml: n, _extensions: Object, lang: "", _name: "smAck", _eventname: "stream:management:ack"…}
raw:incoming <a h='28' xmlns='urn:xmpp:sm:3'/>
raw:outgoing <r xmlns="urn:xmpp:sm:3"/>
iq Object {discoInfo: Object, id: "6de5f060-4ef2-469d-a932-c544854797d2", to: 235.n.JID, from: 235.n.JID, type: "result"…}
stanza Object {discoInfo: Object, id: "6de5f060-4ef2-469d-a932-c544854797d2", to: 235.n.JID, from: 235.n.JID, type: "result"…}
id:6de5f060-4ef2-469d-a932-c544854797d2 Object {discoInfo: Object, id: "6de5f060-4ef2-469d-a932-c544854797d2", to: 235.n.JID, from: 235.n.JID, type: "result"…}
stream:data i {xml: n, _extensions: Object, _name: "iq", _eventname: undefined, _NS: "jabber:client"…}
raw:incoming <iq type='result' to='anon@kdex.de/ratchet-84ea08c8-c332-410d-8965-03f340dcbfb1' from='anon@kdex.de/ratchet-84ea08c8-c332-410d-8965-03f340dcbfb1' id='6de5f060-4ef2-469d-a932-c544854797d2' xmlns='jabber:client'><query xmlns='http://jabber.org/protocol/disco#info'><identity type='web' category='client'/></query></iq>
stream:management:ack Object {h: 29}
stanza:acked i {xml: n, _extensions: Object, _name: "iq", _eventname: undefined, _NS: "jabber:client"…}
stream:data i {xml: n, _extensions: Object, lang: "", _name: "smAck", _eventname: "stream:management:ack"…}
raw:incoming <a h='29' xmlns='urn:xmpp:sm:3'/>
```

Note that first, the success handler is executed using a **prematurely** built object (it's completely empty). In the further response, the object seems to be built. Note that even though the object is built, important properties (such as `features`) are missing.

Providing another JID than the own client's will result in the same behavior. It seems currently impossible to get another stanza.io client's `features`.

Function calls like these (that is, getting my own disco info) shouldn't be necessary anyway (I know that this information is stored in `client.disco`), but AFAIR this **did** work in 6.x.

Is this still compliant to the standard? It feels like a bug, though.

**Comment by legastero** [comment] 2015-01-05 19:27
I've not been able to reproduce this in `7.0.1`. How often does it occur for you?

This was a reliably produceable issue in `6.x` because it was actually capturing the received iq-get request and treating that as the result (and that would look like an empty `discoInfo` object). That is supposed to be fixed in `7.x`

**Comment by kdex** [comment] 2015-01-05 21:32
It seems to work just fine on `demo.html`, given that discoInfo.features.length === 1 is normal (I expected a lot more than that, it has "http://jabber.org/protocol/pubsub#publish" as only feature). It also has an identity property, and until now, I couldn't reproduce having the same undeterminism within `demo.html`. Only discoInfos that look a little too small to me.

But I'm really not doing a lot more than `demo.html` does, anyway. It's not just the app itself, it's basically every call sent from DevTools responding in this manner (not for `demo.html`, it seems…).

**Comment by legastero** [comment] 2015-01-05 21:52
Ok, so something is still odd if demo.html is only giving you one feature. It should be giving you ~60 of them. Does `client.disco.features['']` give you the full set of features or is that also truncated?

**Comment by kdex** [comment] 2015-01-05 22:09
Yes, `client.disco.features['']` is giving me the full ≈60 features. By the way, I just noticed that

```
client.getDiscoInfo(client.config.jid.full, null, function(error, success) {
    console.warn("Responses: ", error, success);
});
```

will actually be sent out to the wrong client in `demo.html`, namely the resource that I entered in the input (which is actually not the resouce that the client actually has). Therefore, this upper call will always result in a timeout. Is this behavior intended?

**Comment by legastero** [comment] 2015-01-05 22:14
Intended. You'd want to use `client.jid.full` instead of `client.config.jid`, because the first is always what you were actually assigned during binding (event the localpart could have changed, not just resource).

**Comment by kdex** [comment] 2015-01-05 22:28
I see, thanks. :)

This might have something to do with my app then; I might register features in an unintended way, which destroys the correct behavior (returning a discoInfo with features) for 

```
client.getDiscoInfo(client.jid.full, null, function(error, success) {
    console.warn("Responses: ", error, success.discoInfo);
});
```

Currently, I define a handfull of stanzas at runtime and pass it to `client.use` before `client.connect` is executed. These stanza functions start with

```js
client.disco.addFeature(NS);
```

with NS being their namespace. Am I supposed to add it to my feature list by just pushing it into the array, maybe?

**Closed** 2017-02-02 09:33 UTC
